#!/bin/bash
read -p 'Press any key to continue...'

echo 'Preparing Package Installer.'
sudo apt-get update
sudo apt-get install git usbmuxd make inotify-tools automake autoconf libtool pkg-config gcc inotify-tools cython doxygen python3 -y
cd ~

echo 'Getting dependency openssl/openssl for package libimobiledevice/libimobiledevice'
git clone https://github.com/openssl/openssl.git ~/.pkginst/openssl
cd ~/.pkginst/openssl/
./config
echo 'Compiling package OpenSSL'
make
echo 'Installing package OpenSSL'
sudo make install
echo 'Testing package OpenSSL'
openssl version
read -p 'Press enter if you do not get an error. If you do, please press ctrl-c (linux) or cmd+c (osx).'
cd ~

echo 'Getting dependency libimobiledevice/libplist for package libimobiledevice/libimobiledevice'
git clone https://github.com/libimobiledevice/libplist.git ~/.pkginst/libplist
cd ~/.pkginst/libplist
echo 'Preparing package libplist'
./autogen.sh
echo 'Compiling package libplist'
make
echo 'Installing package libplist'
sudo make install
cd ~

echo 'Getting dependency libimobiledevice/libusbmuxd for package libimobiledevice/libimobiledevice'
git clone https://github.com/libimobiledevice/libusbmuxd.git ~/.pkginst/libusbmuxd
cd ~/.pkginst/libusbmuxd
echo 'Preparing package libusbmuxd'
./autogen.sh
echo 'Compiling package libusbmuxd'
make
echo 'Installing package libusbmuxd'
sudo make install
cd ~

echo 'Getting package libimobiledevice/libimobiledevice'
git clone https://github.com/libimobiledevice/libimobiledevice.git ~/.pkginst/libimobiledevice
cd ~/.pkginst/libimobiledevice/
echo 'Preparing package libimobiledevice'
./autogen.sh
echo 'Compiling package libimobiledevice'
make
echo 'Installing package libimobiledevice'
sudo make install
cd ~

echo 'Cleaning up...'
rm -rf ~/.pkginst
echo "Done!"
